server.port=8082
spring.application.name=kafka_demo_consumer

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=shivam-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.kafka.model;

spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.kafka.model

